/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * configFrame.java
 *
 * Created on 7-jan-2011, 16:51:30
 */

package view;

import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author 09068007
 */
public class ConfigFrame extends javax.swing.JFrame {
    private Spel spel;
    private HapperFrame happerframe;
    /** Creates new form configFrame */
    public ConfigFrame(Spel spel,HapperFrame happerframe) {
        this.spel = spel;
        this.happerframe = happerframe;
        
        initComponents();
    }

    public void setOpties(){
        zwarteBlokkenField.setText(Integer.toString(spel.getAantalZwarteBlokken()));
        blauweBlokkenField.setText(Integer.toString(spel.getAantalBlauweBlokken()));
        xHorField.setText(Integer.toString(spel.getXHor()));
        yVertField.setText(Integer.toString(spel.getYVert()));
        if(spel.getHapper() instanceof SlimmeHapper){
            happerField.setSelectedIndex(0);
        }
        if(spel.getHapper() instanceof DommeHapper){
            happerField.setSelectedIndex(1);
        }
        if(spel.getHapper() instanceof BangeHapper){
            happerField.setSelectedIndex(2);
        }


    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        zwarteBlokkenField = new javax.swing.JTextField();
        blauweBlokkenField = new javax.swing.JTextField();
        opslaan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        xHorField = new javax.swing.JTextField();
        yVertField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        happerField = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jButton1.setText("Sluiten");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        zwarteBlokkenField.setText("jTextField1");
        zwarteBlokkenField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zwarteBlokkenFieldActionPerformed(evt);
            }
        });

        blauweBlokkenField.setText("jTextField1");

        opslaan.setText("Opslaan");
        opslaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opslaanActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/zwarteblok.JPG"))); // NOI18N
        jLabel1.setText("Aantal zwarte blokken:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blauweblok.JPG"))); // NOI18N
        jLabel2.setText("Aantal blauwe blokken:");

        xHorField.setText("jTextField1");

        yVertField.setText("jTextField1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/happer.png"))); // NOI18N
        jLabel3.setText("Happer AI:");

        jLabel4.setText("X Breedte speelveld:");

        jLabel5.setText("Y Hoogte speelveld:");

        happerField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Slim", "Dom", "Bang" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(happerField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yVertField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(xHorField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(opslaan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(blauweBlokkenField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(zwarteBlokkenField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zwarteBlokkenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blauweBlokkenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(happerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xHorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yVertField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opslaan)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        this.setVisible(false);
        happerframe.setFocusableWindowState(true);
        happerframe.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void opslaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opslaanActionPerformed
        // TODO add your handling code here:
        try {
            int aantalZwarteBlokken = Integer.parseInt(zwarteBlokkenField.getText());
            int aantalBlauweBlokken = Integer.parseInt(blauweBlokkenField.getText());
            int xHor = Integer.parseInt(xHorField.getText());
            int yVert = Integer.parseInt(yVertField.getText());

            if((xHor*yVert)>(aantalZwarteBlokken+aantalBlauweBlokken+2)){
                spel.setAantalZwarteBlokken(aantalZwarteBlokken);
                spel.setAantalZwarteBlokken(aantalZwarteBlokken);
                spel.setAantalBlauweBlokken(aantalBlauweBlokken);
                spel.setXHor(xHor);
                spel.setYVert(yVert);
                spel.resetSpel();
                if(happerField.getSelectedIndex()==0){
                    spel.setHapper(new SlimmeHapper(spel.getSpelVakken()[xHor-1][yVert-1], spel));
                }
                if(happerField.getSelectedIndex()==1){
                    spel.setHapper(new DommeHapper(spel.getSpelVakken()[xHor-1][yVert-1], spel));
                }
                if(happerField.getSelectedIndex()==2){
                    spel.setHapper(new BangeHapper(spel.getSpelVakken()[xHor-1][yVert-1], spel));
                }                
                this.setVisible(false);
                happerframe.resizeSpeelveld(spel.getXHor(), spel.getYVert());
                happerframe.setFocusableWindowState(true);
                happerframe.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Teveel blokken voor speelveld." +
                        "\n Aantal blokken: "+(aantalZwarteBlokken+aantalBlauweBlokken)+
                        "\n Beschikbare vakken: "+(xHor*yVert-2));
            }
            
        } catch (NumberFormatException E) {
            JOptionPane.showMessageDialog(null, "Fout met invoer");
        }
        




    }//GEN-LAST:event_opslaanActionPerformed

    private void zwarteBlokkenFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zwarteBlokkenFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zwarteBlokkenFieldActionPerformed

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigFrame().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField blauweBlokkenField;
    private javax.swing.JComboBox happerField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton opslaan;
    private javax.swing.JTextField xHorField;
    private javax.swing.JTextField yVertField;
    private javax.swing.JTextField zwarteBlokkenField;
    // End of variables declaration//GEN-END:variables

}
